import { BusinessConfig, RoleType, User, UserPermission } from './types';

// Cuentas extraídas de las capturas de pantalla de Maxwell Chacón (Banco LAFISE)
export const DEVELOPER_INFO = {
  name: 'Maxwell Chacón',
  cedula: '2012904950006A',
  email: 'ing.chacon.maxwell@gmail.com',
  bankName: 'Banco LAFISE Bancentro',
  accounts: [
    {
      type: 'Cuenta Amigo (Córdobas C$)',
      currency: 'NIO',
      symbol: 'C$',
      number: '138027529',
      balanceHint: 'C$ 103.95',
      badge: 'Principal Córdobas',
      icon: 'wallet',
    },
    {
      type: 'Cuenta Amigo (Dólares $)',
      currency: 'USD',
      symbol: '$',
      number: '133258435',
      balanceHint: '$ 1.51',
      badge: 'Principal Dólares',
      icon: 'dollar-sign',
    },
    {
      type: 'Cuenta Digital',
      currency: 'NIO',
      symbol: 'C$',
      number: '133238477',
      badge: 'Digital LAFISE',
      icon: 'smartphone',
    },
  ],
  licenseTerms: {
    propertyOf: 'Maxwell Chacón con cédula 2012904950006A',
    commercialRights: 'Libre para usar en negocios. Se requiere autorización previa y por escrito del autor para distribuir, revender o sublicenciar el código fuente con fines comerciales masivos.',
    contact: 'ing.chacon.maxwell@gmail.com',
  },
};

export const DEFAULT_BUSINESS_CONFIG: BusinessConfig = {
  name: 'Comercial & Distribuidora La Excelencia',
  commercialName: 'La Excelencia S.A.',
  taxId: 'J0310000123456',
  email: 'ventas@laexcelencia.com',
  phone: '+505 8888-9999 / 2222-3333',
  address: 'Rotonda Metrocentro 2 cuadras al norte, Módulo B-12',
  city: 'Managua',
  country: 'Nicaragua',
  currencySymbol: 'C$',
  currencyName: 'Córdobas (NIO)',
  exchangeRateUsd: 36.62,
  taxRatePercent: 0,
  logoUrl: '',
  invoiceSeries: 'FAC-01',
  resolutionNumber: 'DGI-RESOL-2026-004582',
  resolutionDate: '2026-01-15',
  invoiceHeaderMessage: '¡Gracias por preferir nuestros productos de alta calidad!',
  invoiceFooterMessage: 'Régimen General. Autorizado por DGI. Documento Fiscal Electrónico.',
  autoCloudSync: true,
  driveBackupEnabled: true,
  lastBackupDate: new Date().toISOString(),
  creatorCopyright: 'Maxwell Chacón',
  creatorCedula: '2012904950006A',
  creatorEmail: 'ing.chacon.maxwell@gmail.com',
};

export const DEFAULT_PERMISSIONS: Record<RoleType, UserPermission[]> = {
  superadmin: [
    { module: 'pos', create: true, read: true, update: true, delete: true },
    { module: 'inventory', create: true, read: true, update: true, delete: true },
    { module: 'kardex', create: true, read: true, update: true, delete: true },
    { module: 'purchases', create: true, read: true, update: true, delete: true },
    { module: 'credits', create: true, read: true, update: true, delete: true },
    { module: 'cash', create: true, read: true, update: true, delete: true },
    { module: 'contacts', create: true, read: true, update: true, delete: true },
    { module: 'reports', create: true, read: true, update: true, delete: true },
    { module: 'users', create: true, read: true, update: true, delete: true },
    { module: 'settings', create: true, read: true, update: true, delete: true },
    { module: 'api', create: true, read: true, update: true, delete: true },
  ],
  admin: [
    { module: 'pos', create: true, read: true, update: true, delete: true },
    { module: 'inventory', create: true, read: true, update: true, delete: true },
    { module: 'kardex', create: true, read: true, update: true, delete: false },
    { module: 'purchases', create: true, read: true, update: true, delete: true },
    { module: 'credits', create: true, read: true, update: true, delete: true },
    { module: 'cash', create: true, read: true, update: true, delete: true },
    { module: 'contacts', create: true, read: true, update: true, delete: true },
    { module: 'reports', create: true, read: true, update: true, delete: false },
    { module: 'users', create: false, read: true, update: false, delete: false },
    { module: 'settings', create: false, read: true, update: true, delete: false },
    { module: 'api', create: true, read: true, update: true, delete: false },
  ],
  cajero: [
    { module: 'pos', create: true, read: true, update: false, delete: false },
    { module: 'inventory', create: false, read: true, update: false, delete: false },
    { module: 'kardex', create: false, read: false, update: false, delete: false },
    { module: 'purchases', create: false, read: false, update: false, delete: false },
    { module: 'credits', create: true, read: true, update: false, delete: false },
    { module: 'cash', create: true, read: true, update: true, delete: false },
    { module: 'contacts', create: true, read: true, update: false, delete: false },
    { module: 'reports', create: false, read: false, update: false, delete: false },
    { module: 'users', create: false, read: false, update: false, delete: false },
    { module: 'settings', create: false, read: false, update: false, delete: false },
    { module: 'api', create: false, read: false, update: false, delete: false },
  ],
  bodeguero: [
    { module: 'pos', create: false, read: false, update: false, delete: false },
    { module: 'inventory', create: true, read: true, update: true, delete: false },
    { module: 'kardex', create: true, read: true, update: false, delete: false },
    { module: 'purchases', create: true, read: true, update: false, delete: false },
    { module: 'credits', create: false, read: false, update: false, delete: false },
    { module: 'cash', create: false, read: false, update: false, delete: false },
    { module: 'contacts', create: false, read: true, update: false, delete: false },
    { module: 'reports', create: false, read: true, update: false, delete: false },
    { module: 'users', create: false, read: false, update: false, delete: false },
    { module: 'settings', create: false, read: false, update: false, delete: false },
    { module: 'api', create: false, read: false, update: false, delete: false },
  ],
  contador: [
    { module: 'pos', create: false, read: true, update: false, delete: false },
    { module: 'inventory', create: false, read: true, update: false, delete: false },
    { module: 'kardex', create: false, read: true, update: false, delete: false },
    { module: 'purchases', create: false, read: true, update: false, delete: false },
    { module: 'credits', create: true, read: true, update: true, delete: false },
    { module: 'cash', create: false, read: true, update: false, delete: false },
    { module: 'contacts', create: false, read: true, update: false, delete: false },
    { module: 'reports', create: true, read: true, update: true, delete: true },
    { module: 'users', create: false, read: false, update: false, delete: false },
    { module: 'settings', create: false, read: true, update: false, delete: false },
    { module: 'api', create: false, read: true, update: false, delete: false },
  ],
};

export const ROLE_PERMISSIONS = DEFAULT_PERMISSIONS;

export const INITIAL_USERS: User[] = [
  {
    id: 'u-1',
    name: 'Maxwell Chacón',
    username: 'mchacon',
    email: 'ing.chacon.maxwell@gmail.com',
    role: 'superadmin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+505 8888-0001',
    lastLogin: 'Hace 5 minutos',
    permissions: DEFAULT_PERMISSIONS.superadmin,
  },
  {
    id: 'u-2',
    name: 'Elena Rostrán',
    username: 'erostran',
    email: 'elena@laexcelencia.com',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+505 8712-3456',
    lastLogin: 'Hoy 08:30 AM',
    permissions: DEFAULT_PERMISSIONS.admin,
  },
  {
    id: 'u-3',
    name: 'Carlos Mendoza',
    username: 'cmendoza',
    email: 'carlos.caja@laexcelencia.com',
    role: 'cajero',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+505 8923-4567',
    lastLogin: 'Hoy 09:15 AM',
    permissions: DEFAULT_PERMISSIONS.cajero,
  },
  {
    id: 'u-4',
    name: 'Roberto Gómez',
    username: 'rgomez',
    email: 'almacen@laexcelencia.com',
    role: 'bodeguero',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    active: true,
    phone: '+505 8634-5678',
    lastLogin: 'Ayer 05:40 PM',
    permissions: DEFAULT_PERMISSIONS.bodeguero,
  },
];

export const CATEGORIES = [
  'Bebidas & Licores',
  'Alimentos & Granos Básicos',
  'Lácteos y Embutidos',
  'Limpieza y Hogar',
  'Cuidado Personal',
  'Ferretería y Herramientas',
  'Tecnología y Accesorios',
  'Servicios Profesionales',
];

export const BRANDS = [
  'Nestlé',
  'Unilever',
  'Coca Cola',
  'Colgate-Palmolive',
  'Bimbo',
  'P&G',
  'Maseca',
  'Genérico',
];

export const UNITS: { code: string; name: string; isScale: boolean }[] = [
  { code: 'UND', name: 'Unidad (Pieza)', isScale: false },
  { code: 'KG', name: 'Kilogramo (Báscula)', isScale: true },
  { code: 'LB', name: 'Libra (Báscula)', isScale: true },
  { code: 'LT', name: 'Litro', isScale: false },
  { code: 'MT', name: 'Metro Lineal', isScale: false },
  { code: 'CAJA', name: 'Caja Master', isScale: false },
  { code: 'DOC', name: 'Docena (12)', isScale: false },
  { code: 'PAQ', name: 'Paquete / Sixpack', isScale: false },
];
